cmake_minimum_required(VERSION 3.8)
project(dog_factory_control)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(trajectory_msgs REQUIRED)
find_package(std_srvs REQUIRED)
add_executable(jump_controller_cpp src/jump_controller.cpp)
ament_target_dependencies(jump_controller_cpp rclcpp trajectory_msgs std_srvs)
install(TARGETS jump_controller_cpp DESTINATION lib/${PROJECT_NAME})
install(PROGRAMS dog_factory_control/autonomy_node.py dog_factory_control/keyboard_teleop.py DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY config launch DESTINATION share/${PROJECT_NAME})
ament_package()
